changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: 新增
      labels:
        - enhancement
        - feat
    - title: 修复
      labels:
        - bug
        - fix
    - title: 优化与维护
      labels:
        - documentation
        - dependencies
        - performance
        - refactor
    - title: 其他变更
      labels:
        - "*"
